In [ ]:
[34,235,23,45,22,None,]

We encounter cells that are empyt,null or undefined. These are called missing values - data points that were expected to record but were not recorded.

- Survey non-response
- System failure
- Data Entry error
- Deliberate omission
- Data migration

<h2>Types of missing values</h2>

- MCAR - Missing completely at random
- MAR - Missing at random
- MNAR - Missing not at random

<h3>MCAR</h3>
The probability of a value being missed has absolutely no relationship with any variable in the dataset.

<h3>MAR</h3>
The missingness is related to observed data, but not the missing values themselves

<h3>MNAR</h3>
The missingness depends on the observed value itself. This is hardest to handle.

<h2>Methods to handle missing values</h2>

1. Removing missing values(Deletion Technique)

    1.1 Row Deletion(Listwise deletion)
    
    1.2 Column Deletion(Dropping features)

2. Imputation

    2.1 Univariate Imputation
        
        - Numerical Value Imputation
        - Categorical value Imputation
    
    2.2 Multivariate Imputation

        - KNN Imputer
        - Iterative Imputer

In [1]:
import pandas as pd
import numpy as np

data = {
    'Name':["Rohan","Krish","Bob","Sohit","Neha","Mayank"],
    'Age':[24,np.nan,34,24,np.nan,35],
    'Score':[85,90,np.nan,88,92,96],
    'Attendance':[100,90,80,np.nan,87,92]
}

df = pd.DataFrame(data)
df

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
1   Krish   NaN   90.0        90.0
2     Bob  34.0    NaN        80.0
3   Sohit  24.0   88.0         NaN
4    Neha   NaN   92.0        87.0
5  Mayank  35.0   96.0        92.0

In [2]:
df.isnull().sum()

Name          0
Age           2
Score         1
Attendance    1
dtype: int64

In [3]:
round(df.isnull().mean()*100,2)

Name           0.00
Age           33.33
Score         16.67
Attendance    16.67
dtype: float64

<h3>Row deletion</h3>

When it is good to use?

- Low percentage: if <5%  data is missing
- MCAR: The missingness has no hidden pattern
- Large Dataset: If you have million's of rows, losing 1000 rows won't hurt model's performance.


When not to use it?

- Small dataset: If you only have 100 rows, every single rows is precious.
- Bias Risk: If only 'High income' individuals refused  to answer the survey, dropping those rows removes your "High income" Representation entirely.

In [4]:
df_dropped = df.dropna()

In [5]:
df

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
1   Krish   NaN   90.0        90.0
2     Bob  34.0    NaN        80.0
3   Sohit  24.0   88.0         NaN
4    Neha   NaN   92.0        87.0
5  Mayank  35.0   96.0        92.0

In [6]:
df_dropped

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
5  Mayank  35.0   96.0        92.0

In [7]:
df_subset = df.dropna(subset=['Score','Attendance'])

In [8]:
df_subset

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
1   Krish   NaN   90.0        90.0
4    Neha   NaN   92.0        87.0
5  Mayank  35.0   96.0        92.0

In [11]:
df_thresh = df.dropna(thresh=3)

In [12]:
df_thresh

     Name   Age  Score  Attendance
0   Rohan  24.0   85.0       100.0
1   Krish   NaN   90.0        90.0
2     Bob  34.0    NaN        80.0
3   Sohit  24.0   88.0         NaN
4    Neha   NaN   92.0        87.0
5  Mayank  35.0   96.0        92.0

### Column deletion

In [13]:
df['Notes'] = [np.nan,'Good',np.nan,np.nan,np.nan,'Average']

In [14]:
df

     Name   Age  Score  Attendance    Notes
0   Rohan  24.0   85.0       100.0      NaN
1   Krish   NaN   90.0        90.0     Good
2     Bob  34.0    NaN        80.0      NaN
3   Sohit  24.0   88.0         NaN      NaN
4    Neha   NaN   92.0        87.0      NaN
5  Mayank  35.0   96.0        92.0  Average

In [15]:
missing_pct = round(df.isnull().mean()*100,2)

In [16]:
missing_pct

Name           0.00
Age           33.33
Score         16.67
Attendance    16.67
Notes         66.67
dtype: float64

In [17]:
missing_pct.index

Index(['Name', 'Age', 'Score', 'Attendance', 'Notes'], dtype='str')

In [18]:
missing_pct.values

array([ 0.  , 33.33, 16.67, 16.67, 66.67])

In [20]:
limit = 30

cols_to_drop = missing_pct[missing_pct>limit].index
cols_to_drop

Index(['Age', 'Notes'], dtype='str')

In [21]:
df_reduced = df.drop(columns=cols_to_drop)

In [22]:
df_reduced

     Name  Score  Attendance
0   Rohan   85.0       100.0
1   Krish   90.0        90.0
2     Bob    NaN        80.0
3   Sohit   88.0         NaN
4    Neha   92.0        87.0
5  Mayank   96.0        92.0