## Sampling

Sampling is the process of selecting a subset of data from a larger population.

Instead of studying every data point(population) we study only a representation subset(sample).

Population = Every customer of Amazon.

sample = 10000 randomly selected customers.

### Types of sampling

- Simple random sampling
- Stratified sampling
- Systematic Sampling
- cluster sampling

!(data)[https://archive.ics.uci.edu/dataset/352/online+retail]

In [1]:
import pandas as pd

data = pd.read_excel("../../data/Online Retail.xlsx",sheet_name="Online Retail")

In [4]:
data.shape

(541909, 8)

### Simple Random sampling

Every row has an equal probability of being select.

In [9]:
sample_srs = data.sample(n=10000,random_state=42)
print(sample_srs.shape[0])
sample_srs.head(20)

10000

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
209268,555200,71459,HANGING JAM JAR T-LIGHT HOLDER,24,2011-06-01 12:05:00,0.85,17315.0,United Kingdom
207108,554974,21128,GOLD FISHING GNOME,4,2011-05-27 17:14:00,6.95,14031.0,United Kingdom
167085,550972,21086,SET/6 RED SPOTTY PAPER CUPS,4,2011-04-21 17:05:00,0.65,14031.0,United Kingdom
471836,576652,22812,PACK 3 BOXES CHRISTMAS PANETTONE,3,2011-11-16 10:39:00,1.95,17198.0,United Kingdom
115865,546157,22180,RETROSPOT LAMP,2,2011-03-10 08:40:00,9.95,13502.0,United Kingdom
465024,576200,82482,WOODEN PICTURE FRAME WHITE FINISH,2,2011-11-14 12:14:00,2.95,15572.0,United Kingdom
477777,577076,22614,PACK OF 12 SPACEBOY TISSUES,12,2011-11-17 15:08:00,0.39,14362.0,United Kingdom
367855,568909,22596,CHRISTMAS STAR WISH LIST CHALKBOARD,12,2011-09-29 13:38:00,1.25,16818.0,United Kingdom
491657,578072,21109,LARGE CAKE TOWEL CHOCOLATE SPOTS,1,2011-11-22 16:02:00,6.75,17759.0,United Kingdom
269641,560491,23297,SET 40 HEART SHAPE PETIT FOUR CASES,2,2011-07-19 10:51:00,1.65,12415.0,Australia
111488,545721,82484,WOOD BLACK BOARD ANT WHITE FINISH,1,2011-03-07 10:52:00,7.90,15039.0,United Kingdom
427787,573399,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,18,2011-10-30 15:35:00,0.79,13949.0,United Kingdom
175354,551954,22799,SWEETHEART WIRE FRUIT BOWL,1,2011-05-05 12:13:00,8.50,14515.0,United Kingdom
306249,563745,22115,METAL SIGN EMPIRE TEA,12,2011-08-19 09:38:00,0.79,15159.0,United Kingdom
47558,540418,22161,HEART DECORATION RUSTIC HANGING,5,2011-01-07 11:04:00,0.81,NaN,United Kingdom
116334,546237,84508A,CAMOUFLAGE DESIGN TEDDY,6,2011-03-10 12:50:00,2.55,16625.0,United Kingdom
136911,548005,21499,BLUE POLKADOT WRAP,25,2011-03-29 10:49:00,0.42,14128.0,United Kingdom
31630,539000,22622,BOX OF VINTAGE ALPHABET BLOCKS,4,2010-12-15 12:27:00,9.95,13092.0,United Kingdom
111243,545715,82600,NO SINGING METAL SIGN,1,2011-03-07 10:13:00,4.13,NaN,United Kingdom
414833,C572489,22465,HANGING METAL STAR LANTERN,-5,2011-10-24 13:59:00,1.65,17119.0,United Kingdom

In [10]:
sample_srs = data.sample(frac=0.2,random_state=42)
print(sample_srs.shape[0])
sample_srs.head(20)

108382

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
209268,555200,71459,HANGING JAM JAR T-LIGHT HOLDER,24,2011-06-01 12:05:00,0.85,17315.0,United Kingdom
207108,554974,21128,GOLD FISHING GNOME,4,2011-05-27 17:14:00,6.95,14031.0,United Kingdom
167085,550972,21086,SET/6 RED SPOTTY PAPER CUPS,4,2011-04-21 17:05:00,0.65,14031.0,United Kingdom
471836,576652,22812,PACK 3 BOXES CHRISTMAS PANETTONE,3,2011-11-16 10:39:00,1.95,17198.0,United Kingdom
115865,546157,22180,RETROSPOT LAMP,2,2011-03-10 08:40:00,9.95,13502.0,United Kingdom
465024,576200,82482,WOODEN PICTURE FRAME WHITE FINISH,2,2011-11-14 12:14:00,2.95,15572.0,United Kingdom
477777,577076,22614,PACK OF 12 SPACEBOY TISSUES,12,2011-11-17 15:08:00,0.39,14362.0,United Kingdom
367855,568909,22596,CHRISTMAS STAR WISH LIST CHALKBOARD,12,2011-09-29 13:38:00,1.25,16818.0,United Kingdom
491657,578072,21109,LARGE CAKE TOWEL CHOCOLATE SPOTS,1,2011-11-22 16:02:00,6.75,17759.0,United Kingdom
269641,560491,23297,SET 40 HEART SHAPE PETIT FOUR CASES,2,2011-07-19 10:51:00,1.65,12415.0,Australia
111488,545721,82484,WOOD BLACK BOARD ANT WHITE FINISH,1,2011-03-07 10:52:00,7.90,15039.0,United Kingdom
427787,573399,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,18,2011-10-30 15:35:00,0.79,13949.0,United Kingdom
175354,551954,22799,SWEETHEART WIRE FRUIT BOWL,1,2011-05-05 12:13:00,8.50,14515.0,United Kingdom
306249,563745,22115,METAL SIGN EMPIRE TEA,12,2011-08-19 09:38:00,0.79,15159.0,United Kingdom
47558,540418,22161,HEART DECORATION RUSTIC HANGING,5,2011-01-07 11:04:00,0.81,NaN,United Kingdom
116334,546237,84508A,CAMOUFLAGE DESIGN TEDDY,6,2011-03-10 12:50:00,2.55,16625.0,United Kingdom
136911,548005,21499,BLUE POLKADOT WRAP,25,2011-03-29 10:49:00,0.42,14128.0,United Kingdom
31630,539000,22622,BOX OF VINTAGE ALPHABET BLOCKS,4,2010-12-15 12:27:00,9.95,13092.0,United Kingdom
111243,545715,82600,NO SINGING METAL SIGN,1,2011-03-07 10:13:00,4.13,NaN,United Kingdom
414833,C572489,22465,HANGING METAL STAR LANTERN,-5,2011-10-24 13:59:00,1.65,17119.0,United Kingdom

In [11]:
data['Country'].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

## Train Test split

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    data.drop('Country',axis=1),
    data['Country'],
    test_size = 0.2,
    random_state=42
)

In [18]:
data.shape[0]-X_test.shape[0]

433527

In [15]:
y_train.head()

431701    United Kingdom
293936              EIRE
64358     United Kingdom
174874    United Kingdom
280634    United Kingdom
Name: Country, dtype: str

### Stratified Sampling

Suppose we want sampled dataset to maintain the same proportion of country

In [19]:
X = data.drop('Country',axis=1)
y = data['Country']

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state=42,
    stratify = y
)

In [25]:
y.value_counts()/y.shape[0]

Country
United Kingdom          0.914320
Germany                 0.017521
France                  0.015790
EIRE                    0.015124
Spain                   0.004674
Netherlands             0.004375
Belgium                 0.003818
Switzerland             0.003694
Portugal                0.002803
Australia               0.002323
Norway                  0.002004
Italy                   0.001482
Channel Islands         0.001399
Finland                 0.001283
Cyprus                  0.001148
Sweden                  0.000853
Unspecified             0.000823
Austria                 0.000740
Denmark                 0.000718
Japan                   0.000661
Poland                  0.000629
Israel                  0.000548
USA                     0.000537
Hong Kong               0.000531
Singapore               0.000423
Iceland                 0.000336
Canada                  0.000279
Greece                  0.000269
Malta                   0.000234
United Arab Emirates    0.000125
European Community      0.000113
RSA                     0.000107
Lebanon                 0.000083
Lithuania               0.000065
Brazil                  0.000059
Czech Republic          0.000055
Bahrain                 0.000035
Saudi Arabia            0.000018
Name: count, dtype: float64

In [26]:
y_test.value_counts()/y_test.shape[0]

Country
United Kingdom          0.914322
Germany                 0.017521
France                  0.015796
EIRE                    0.015122
Spain                   0.004678
Netherlands             0.004373
Belgium                 0.003820
Switzerland             0.003691
Portugal                0.002805
Australia               0.002325
Norway                  0.002002
Italy                   0.001485
Channel Islands         0.001402
Finland                 0.001283
Cyprus                  0.001144
Sweden                  0.000849
Unspecified             0.000821
Austria                 0.000738
Denmark                 0.000720
Japan                   0.000664
Poland                  0.000627
Israel                  0.000544
USA                     0.000535
Hong Kong               0.000535
Singapore               0.000424
Iceland                 0.000332
Canada                  0.000277
Greece                  0.000268
Malta                   0.000231
United Arab Emirates    0.000129
RSA                     0.000111
European Community      0.000111
Lebanon                 0.000083
Lithuania               0.000065
Brazil                  0.000055
Czech Republic          0.000055
Bahrain                 0.000037
Saudi Arabia            0.000018
Name: count, dtype: float64

### Systematic Sampling

We want each kth record from data

In [30]:
import numpy as np

In [33]:
k = 10
start = np.random.randint(0,k)
sample_systematic = data.iloc[start::k]

print(sample_systematic.shape)

(54191, 8)

### Cluster sampling

Assume each country class is a cluster

In [34]:
data['Country'].unique()

<ArrowStringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str

In [35]:
select_cluster = np.random.choice(data['Country'].unique())
print(select_cluster)

Germany

In [36]:
cluster_sample = data[data['Country']==select_cluster]
print(cluster_sample.shape[0])
cluster_sample.head()

9495

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1109,536527,22809,SET OF 6 T-LIGHTS SANTA,6,2010-12-01 13:04:00,2.95,12662.0,Germany
1110,536527,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,6,2010-12-01 13:04:00,2.55,12662.0,Germany
1111,536527,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,2010-12-01 13:04:00,0.85,12662.0,Germany
1112,536527,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,2010-12-01 13:04:00,1.65,12662.0,Germany
1113,536527,22244,3 HOOK HANGER MAGIC GARDEN,12,2010-12-01 13:04:00,1.95,12662.0,Germany