Categorical variables are variables that contain labels instead of numerical values.

### Types of categorical Variables

- Nominal Data
- Ordinal Data

In [1]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [3]:
df['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [4]:
df['deck'] = df['deck'].fillna("C")

In [5]:
df['age'] = df['age'].fillna(df['age'].mean())

In [6]:
df['embarked'] = df['embarked'].fillna("S")

In [7]:
df['embark_town'] = df['embark_town'].fillna('Southampton')

In [8]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
5,0,3,male,29.699118,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True
6,0,1,male,54.000000,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.000000,3,1,21.0750,S,Third,child,False,C,Southampton,no,False
8,1,3,female,27.000000,0,2,11.1333,S,Third,woman,False,C,Southampton,yes,False
9,1,2,female,14.000000,1,0,30.0708,C,Second,child,False,C,Cherbourg,yes,False

### 1. Label Encoding

Assigns a unique integer to each category

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['sex_encoded'] = le.fit_transform(df['sex'])

df[['sex','sex_encoded']].head()

      sex  sex_encoded
0    male            1
1  female            0
2  female            0
3  female            0
4    male            1

In [14]:
education = pd.DataFrame(
    {"education":["High School","Intermediate","Graduate","Post Graduate","PhD"]}
)

education['education_labelEncode'] = le.fit_transform(education['education'])

education

       education  education_labelEncode
0    High School                      1
1   Intermediate                      2
2       Graduate                      0
3  Post Graduate                      4
4            PhD                      3

In [16]:
from sklearn.preprocessing import OrdinalEncoder

categories = [["High School","Intermediate","Graduate","Post Graduate","PhD"]]

oe = OrdinalEncoder(categories=categories)

education[['ordinal_encoded']] = oe.fit_transform(education[['education']])

education

       education  education_labelEncode  ordinal_encoded
0    High School                      1              0.0
1   Intermediate                      2              1.0
2       Graduate                      0              2.0
3  Post Graduate                      4              3.0
4            PhD                      3              4.0

### 2. Ordinal Encoding

Used when categories have order.

In [18]:
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [19]:
categories = [['First','Second','Third']]

In [21]:
oe = OrdinalEncoder(categories=categories)

df[['class_encoded']] = oe.fit_transform(df[['class']])

df[['class','class_encoded']].head(10)

    class  class_encoded
0   Third            2.0
1   First            0.0
2   Third            2.0
3   First            0.0
4   Third            2.0
5   Third            2.0
6   First            0.0
7   Third            2.0
8   Third            2.0
9  Second            1.0

### 3. OneHotEncoder

Create separate column for category

In [22]:
education = pd.DataFrame(
    {"education":["High School","Intermediate","Graduate","Post Graduate","PhD"]}
)

In [29]:
education

       education
0    High School
1   Intermediate
2       Graduate
3  Post Graduate
4            PhD

In [30]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

encoded_data = ohe.fit_transform(education[['education']])

education_encoded = pd.DataFrame(encoded_data,columns=['Graduate','High School','Intermediate','PhD','Post Graduate'])

In [32]:
education_encoded['education'] = education['education']

In [33]:
education_encoded

   Graduate  High School  Intermediate  PhD  Post Graduate      education
0       0.0          1.0           0.0  0.0            0.0    High School
1       0.0          0.0           1.0  0.0            0.0   Intermediate
2       1.0          0.0           0.0  0.0            0.0       Graduate
3       0.0          0.0           0.0  0.0            1.0  Post Graduate
4       0.0          0.0           0.0  1.0            0.0            PhD

In [36]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_encoded,class_encoded
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,1,2.0
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0,0.0
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,0,2.0
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0,0.0
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True,1,2.0
5,0,3,male,29.699118,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True,1,2.0
6,0,1,male,54.000000,0,0,51.8625,S,First,man,True,E,Southampton,no,True,1,0.0
7,0,3,male,2.000000,3,1,21.0750,S,Third,child,False,C,Southampton,no,False,1,2.0
8,1,3,female,27.000000,0,2,11.1333,S,Third,woman,False,C,Southampton,yes,False,0,2.0
9,1,2,female,14.000000,1,0,30.0708,C,Second,child,False,C,Cherbourg,yes,False,0,1.0

In [39]:
ohe = OneHotEncoder(sparse_output=False)

who_data = ohe.fit_transform(df[['who']])
who_data
df[['child','man','woman']] = pd.DataFrame(who_data,columns=['child','man','woman'])

In [40]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_encoded,class_encoded,child,man,woman
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,C,Southampton,no,False,1,2.0,0.0,1.0,0.0
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0,0.0,0.0,0.0,1.0
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True,0,2.0,0.0,0.0,1.0
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0,0.0,0.0,0.0,1.0
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,C,Southampton,no,True,1,2.0,0.0,1.0,0.0
5,0,3,male,29.699118,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True,1,2.0,0.0,1.0,0.0
6,0,1,male,54.000000,0,0,51.8625,S,First,man,True,E,Southampton,no,True,1,0.0,0.0,1.0,0.0
7,0,3,male,2.000000,3,1,21.0750,S,Third,child,False,C,Southampton,no,False,1,2.0,1.0,0.0,0.0
8,1,3,female,27.000000,0,2,11.1333,S,Third,woman,False,C,Southampton,yes,False,0,2.0,0.0,0.0,1.0
9,1,2,female,14.000000,1,0,30.0708,C,Second,child,False,C,Cherbourg,yes,False,0,1.0,1.0,0.0,0.0