<h1>Feature Scaling</h1>

Feature scaling is the process of transforming numerical features so they are on the similar scale.
It helps many machine learning algorithms perform better and converge faster.

Algorithms based on distance or gradients may give more importance to salary.

Algorithms that need scaling:

- KNN
- K-Means
- SVM
- Logistic Regression
- Neural Networks
- PCA

Algorithms that usually don't nees scaling

- Decision Trees
- Random Forest
- XGBoost

In [1]:
from sklearn.datasets import load_wine
import pandas as pd

wine = load_wine()

df = pd.DataFrame(
    wine.data,
    columns = wine.feature_names
)

df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [2]:
df.describe().T[['min','max']]

                                 min      max
alcohol                        11.03    14.83
malic_acid                      0.74     5.80
ash                             1.36     3.23
alcalinity_of_ash              10.60    30.00
magnesium                      70.00   162.00
total_phenols                   0.98     3.88
flavanoids                      0.34     5.08
nonflavanoid_phenols            0.13     0.66
proanthocyanins                 0.41     3.58
color_intensity                 1.28    13.00
hue                             0.48     1.71
od280/od315_of_diluted_wines    1.27     4.00
proline                       278.00  1680.00

1. <h2>Standard Scaling (z-score)</h2>

$$
Z = \frac{X - \mu}{\sigma}
$$

In [3]:
df_sub = df[['proline','ash','malic_acid']]

In [5]:
pl_mean = df_sub['proline'].mean()
pl_std = df_sub['proline'].std()

ash_mean = df_sub['ash'].mean()
ash_std = df_sub['ash'].std()

malic_acid_mean = df_sub['malic_acid'].mean()
malic_acid_std = df_sub['malic_acid'].std()

In [35]:
df_sub.head()

   proline   ash  malic_acid  ...  ash_scaled  malic_acid_scaled  proline_inverse
0   1065.0  2.43        1.71  ...        0.23              -0.56           1064.9
1   1050.0  2.14        1.78  ...       -0.83              -0.50           1049.2
2   1185.0  2.67        2.36  ...        1.11               0.02           1184.6
3   1480.0  2.50        1.95  ...        0.49              -0.35           1480.6
4    735.0  2.87        2.59  ...        1.84               0.23            734.3

[5 rows x 7 columns]

In [13]:
df_sub['proline_scaled'] = round((df_sub['proline'] - pl_mean)/pl_std,2)

In [14]:
df_sub['ash_scaled'] = round((df_sub['ash']-ash_mean)/ash_std,2)

In [15]:
df_sub['malic_acid_scaled'] = round((df_sub['malic_acid']-malic_acid_mean)/malic_acid_std,2)

In [17]:
df_sub.describe().T[['min','max']]

                      min      max
proline            278.00  1680.00
ash                  1.36     3.23
malic_acid           0.74     5.80
proline_scaled      -1.49     2.96
ash_scaled          -3.67     3.15
malic_acid_scaled   -1.43     3.10

Inverse transformation

In [34]:
df_sub['proline_inverse'] = round(df_sub['proline_scaled'] * pl_std + pl_mean,1)

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(df)

scaled_df = pd.DataFrame(scaled_data,columns=df.columns)

scaled_df.head()

    alcohol  malic_acid  ...  od280/od315_of_diluted_wines   proline
0  1.518613   -0.562250  ...                      1.847920  1.013009
1  0.246290   -0.499413  ...                      1.113449  0.965242
2  0.196879    0.021231  ...                      0.788587  1.395148
3  1.691550   -0.346811  ...                      1.184071  2.334574
4  0.295700    0.227694  ...                      0.449601 -0.037874

[5 rows x 13 columns]

In [37]:
inverse_data = scaler.inverse_transform(scaled_df)

inverse_df = pd.DataFrame(inverse_data,columns=df.columns)

inverse_df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [38]:
df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

2. <h2>Min Max Scaler</h2>

$$
X_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}
$$

it ranges [0,1]

In [39]:
df_ = df[['proline','ash','malic_acid']]

proline_min = df_['proline'].min()
proline_max = df_['proline'].max()

ash_min = df_['ash'].min()
ash_max = df_['ash'].max()

malic_acid_min = df_['malic_acid'].min()
malic_acid_max = df_['malic_acid'].max()

In [43]:
df_['proline_scaled'] = round((df_['proline'] - proline_min)/(proline_max-proline_min),2)

In [45]:
df_['ash_scaled'] = round((df_['ash']-ash_min)/(ash_max-ash_min),2)

In [59]:
df_['malic_acid_scaled'] = round((df_['malic_acid']-malic_acid_min)/(malic_acid_max-malic_acid_min),2)

In [62]:
df_.head()

   proline   ash  malic_acid  ...  ash_scaled  malic_acid_scaled  proline_inverse
0   1065.0  2.43        1.71  ...        0.57               0.19          1063.12
1   1050.0  2.14        1.78  ...        0.42               0.21          1049.10
2   1185.0  2.67        2.36  ...        0.70               0.32          1189.30
3   1480.0  2.50        1.95  ...        0.61               0.24          1483.72
4    735.0  2.87        2.59  ...        0.81               0.37           740.66

[5 rows x 7 columns]

In [61]:
df_['proline_inverse']=df_['proline_scaled']*(proline_max-proline_min) + proline_min

In [63]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(df)

scaled_df = pd.DataFrame(scaled_data,columns=df.columns)

scaled_df.head()

    alcohol  malic_acid  ...  od280/od315_of_diluted_wines   proline
0  0.842105    0.191700  ...                      0.970696  0.561341
1  0.571053    0.205534  ...                      0.780220  0.550642
2  0.560526    0.320158  ...                      0.695971  0.646933
3  0.878947    0.239130  ...                      0.798535  0.857347
4  0.581579    0.365613  ...                      0.608059  0.325963

[5 rows x 13 columns]

In [64]:
inverese_data = scaler.fit_transform(scaled_df)

inverse_df = pd.DataFrame(inverse_data,columns=df.columns)

inverse_df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [65]:
df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]